name: Fetch and Summarize Data
on: 
  push:
    branches:
      - master
  schedule:
    - cron: "0 20 * * *"
    
jobs:
  summarize:
    name: summarize
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: npm install
        
      - name: Download and Generate JSON data
        run: node generate.js 2>&1 | tee docs/log.txt

      - name: Publish Latest Data
        run: node publish.js
        
      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          author_name: Automated Action
          author_email: automated@covid19kerala.info
          message: "Update Summary Data"
          add: "docs/*/*.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
